//------------------------------------------------------------------------------
// <auto-generated>
//     Manual stub until ResX designer codegen is configured in the IDE.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace TinyTBS.Content.Strings {
    using System.Resources;

    public static class Strings {
        private static ResourceManager? resourceMan;

        public static ResourceManager ResourceManager =>
            resourceMan ??= new ResourceManager("TinyTBS.Content.Strings.Strings", typeof(Strings).Assembly);

        public static string AppTitle => ResourceManager.GetString(nameof(AppTitle)) ?? "TinyTBS";
    }
}
