<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>TinyTBS.Engine</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Gum.MonoGame" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="MonoGame.Extended" />
    <PackageReference Include="MonoGame.Framework.DesktopGL" />
    <PackageReference Include="NativeFileDialogNET" />
  </ItemGroup>
</Project>
